### ISSUE TITLE
Default timeout is not configurable in the stack.

### ISSUE THREAD

**Issue by karcaw** [pacifica/pacifica-python-downloader#24]
### Pacifica Software versions
pacifica-cli              0.4.0
pacifica-downloader       0.3.5

### Platform Details
any

### Scenario:
Download a large transaction ~1TB

### Steps to Reproduce:
pacifica-cli download --transaction-id <id>

### Expected Result:
A massive tar file is in my current directory

### Actual Result:
Timeout error:
```
Traceback (most recent call last):
  File "/opt/myemsl/bin/pacifica-cli", line 11, in <module>
    sys.exit(main())
  File "/opt/myemsl/lib/python3.6/site-packages/pacifica/cli/__main__.py", line 144, in main
    args.func(args, config_data)
  File "/opt/myemsl/lib/python3.6/site-packages/pacifica/cli/methods.py", line 172, in download
    return dl_obj.transactioninfo(args.destination, resp.json())
  File "/opt/myemsl/lib/python3.6/site-packages/pacifica/downloader/downloader.py", line 54, in transactioninfo
    TransactionInfo.yield_files(transinfo)
  File "/opt/myemsl/lib/python3.6/site-packages/pacifica/downloader/cartapi.py", line 115, in wait_for_cart
    assert resp_status == 'ready'
AssertionError
```

This happens because the timeout here:
https://github.com/pacifica/pacifica-python-downloader/blob/936acd2bd104a0c0f1758963a6e01ed8e307179f/pacifica/downloader/cartapi.py#L95

which is set at 120 seconds, which even on a 10Gb link we can only get 120GB of the files before it will always timeout, as there is no way to set the timeout through the pacifica-cli -> pacifica-downloader stack, and there is not a config option set anywhere.

**Comment by dmlb2000** [comment]
The time out is part of the library API, so this ticket needs to be moved to the CLI repo.

**Comment by karcaw** [comment]
the code in pacifica-cli: https://github.com/pacifica/pacifica-cli/blob/9ec694e2a58b6427db46d8772765f9ce7d719830/pacifica/cli/methods.py#L180
calls:
https://github.com/pacifica/pacifica-python-downloader/blob/936acd2bd104a0c0f1758963a6e01ed8e307179f/pacifica/downloader/downloader.py#L43-53
which does not have a timeout set, and so this one is https://github.com/pacifica/pacifica-python-downloader/blob/936acd2bd104a0c0f1758963a6e01ed8e307179f/pacifica/downloader/cartapi.py#L95
the only place you can change the timeout.  you never call wait_for_cart in this stack from pacifica-cli. and this API does not provide a way to set one in a config file. So this needs to be fixed here first, and then maybe up in pacifica-cli.  It may even be better to detect when progress is not moving forward, such as checking if files are getting staged or not, or if errors are occuring on the backend.

**Comment by dmlb2000** [comment]
Ah, I see where you are wanting a fix.

**Comment by dmlb2000** [comment]
Feel free to put in a pull request, and I'll review.
