### ISSUE TITLE
Downloads and timeouts leave orphaned carts laying about

### ISSUE THREAD

**Issue by karcaw** [pacifica/pacifica-python-downloader#25]
### Pacifica Core Software versions
pacifica-cli 0.4.0
pacifica-downloader 0.3.5

### Platform Details
any

### Scenario:
When a download times out as in #24, or in other cases of failure, the cart that was created is now orphaned.  And since it probably still staging, it is now blocking other cart creation processes.  If the user gets the error, he is just going to retry, which just starts another cart which has a lower chance of even starting a stage before the timeout will happen.

### Steps to Reproduce:
try and download a large(>1TB) cart that times out
or just download a small cart, it still orphans it.

### Expected Result:
timeouts and other errors should be handled better by cleaning up the carts.
once a download is complete, delete the cart so that space is reclaimed on the storage backends.

**Comment by dmlb2000** [comment]
I think this feature should happen in the https://github.com/pacifica/pacifica-cli/issues repository please put this issue over there.
